# Generated by Django 5.0.7 on 2024-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_education_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('github', 'Github'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('adress', 'Adress'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
